#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Branch_Testbed_Android.Resource", IsApplication=true)]

namespace Branch_Testbed_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::BranchXamarinSDK.Droid.Resource.String.library_name = global::Branch_Testbed_Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050010
			public const int buyButton = 2131034128;
			
			// aapt resource value: 0x7f050017
			public const int contentAccessButton = 2131034135;
			
			// aapt resource value: 0x7f050007
			public const int createLinkButton = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int errorDesc = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int errorTitle = 2131034112;
			
			// aapt resource value: 0x7f050015
			public const int firstParamsButton = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int historyButton = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int lastParamsButton = 2131034134;
			
			// aapt resource value: 0x7f050009
			public const int linearLayout1 = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout2 = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int linearLayout3 = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int linearLayout4 = 2131034130;
			
			// aapt resource value: 0x7f050006
			public const int linkText = 2131034118;
			
			// aapt resource value: 0x7f050019
			public const int logButton = 2131034137;
			
			// aapt resource value: 0x7f050003
			public const int logText = 2131034115;
			
			// aapt resource value: 0x7f05000e
			public const int logoutButton = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int redeemButton = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int refreshButton = 2131034125;
			
			// aapt resource value: 0x7f050005
			public const int relativeLayout1 = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int rewardText = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int scrollView1 = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int sendEventButton = 2131034129;
			
			// aapt resource value: 0x7f05000b
			public const int setUserButton = 2131034123;
			
			// aapt resource value: 0x7f050014
			public const int shareButton = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int spotlightButton = 2131034136;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ErrorLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HistoryLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LogLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int branch_key = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
