#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Branch_Testbed_Android.Resource", IsApplication=true)]

namespace Branch_Testbed_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::BranchXamarinSDK.Droid.Resource.String.library_name = global::Branch_Testbed_Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F010000
			public const int buyButton = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int contentAccessButton = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int createLinkButton = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int errorDesc = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int errorTitle = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int firstParamsButton = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int historyButton = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int lastParamsButton = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int linearLayout1 = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int linearLayout2 = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int linearLayout3 = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int linearLayout4 = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int linkText = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int logButton = 2130771981;
			
			// aapt resource value: 0x7F01000F
			public const int logoutButton = 2130771983;
			
			// aapt resource value: 0x7F01000E
			public const int logText = 2130771982;
			
			// aapt resource value: 0x7F010010
			public const int redeemButton = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int refreshButton = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int relativeLayout1 = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int rewardText = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int scrollView1 = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int sendEventButton = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int setUserButton = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int shareButton = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int spotlightButton = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int textView1 = 2130771993;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F020000
			public const int ErrorLayout = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int HistoryLayout = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int LogLayout = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int Main = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int branch_key = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
